import type { Metadata } from "next";
import { Syne } from "next/font/google";
import "@/styles/globals.css";

import Nav from "@/components/nav/nav";

const syne = Syne({ subsets: ["latin"], weight: ["400", "700", "800"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={syne.className}>
        <Nav />
        {children}
      </body>
    </html>
  );
}
